

name: Build And Deploy

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_SCRIPT: build
  CONNECTION: "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
  SETUP_PATH: grauel.net

# Necessary to run shell scripts
permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Repo Name
        run: 'echo "Repo Name: ${{ github.repository }}"'
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Do the build
        run: |
          npm install
          npm run $BUILD_SCRIPT

      - name: Move Files To Files to Server 
        # removed the --del flag, so that other sub folder based projects aren't removed
        # may want a different approach in future to be sure stale files get removed
        run: rsync -a -v ./dist/. $CONNECTION:$SETUP_PATH
